version: "3.8"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mongo-volume:
